### ISSUE TITLE
Automatic detection not working with ansible pycharm installation

### ISSUE THREAD

**Issue by austin-agronick** [alex1701c/JetBrainsRunner#38]
- only using professional addition pycharm
- installed with ansible:
    - https://github.com/reimarstier/ansible-role-jetbrains_installer
    - https://galaxy.ansible.com/reimarstier/jetbrains_installer

With the following playbook configuration:
```
  - role: reimarstier.jetbrains_installer
    vars:
      jetbrains_installer_apps:
        - name: "PyCharm Professional"
      jetbrains_installer_bin_dir: "/opt/bin"
      jetbrains_installer_dir: "/opt"
      jetbrains_installer_remove_old_tools: True
```

Configured manually successfully:
![image](https://user-images.githubusercontent.com/33553701/222342327-e1dbed61-d37a-4b03-a674-247ce4569a9c.png)

Here's the log file, with the manual config removed for privacy:
```
========== Find Available Config Folders ==========
RubyMine /home/austin/.config/JetBrains/RubyMine2022.3
PyCharm /home/austin/.config/JetBrains/PyCharm2022.3
========== Filter Jetbrains Apps ==========
```
